#!/usr/bin/with-contenv sh

[[ "${MODE:-api}" == "api" ]] || ( /usr/bin/s6-stopdisable api && exit 0 )

cd /data

if [[ ${ENV} == "dev" ]]; then
  reload="--reload"
fi

exec uvicorn opa.main:app --host 0.0.0.0 --log-level ${OPA_LOGLEVEL:-info} ${reload}

