version: "3.7"

services:
  api:
    build:
      context: "api"
      dockerfile: Dockerfile-dev
    volumes:
      - "./api/data:/data"
      - ".:/opa-stack"
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:5678:5678" # Only needed for debugging
    environment:
      ENV: dev

    depends_on:
      - mongo
      - rabbitmq
      - redis

  mongo:
    image: "mongo:3.6.16"
    environment:
      MONGO_INITDB_DATABASE: "opa"
    volumes:
      - "./mongo/entrypoint:/docker-entrypoint-initdb.d"

  mongo-dashboard:
    image: mongo-express
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_AUTH_DATABASE: opa
      ME_CONFIG_MONGODB_AUTH_USERNAME: mongo
      ME_CONFIG_MONGODB_AUTH_PASSWORD: mongo

  rabbitmq:
    image: "rabbitmq:3.8-management"
    ports:
      - "15672:15672" # Management port

  redis:
    image: "redis:5.0.7"
